version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=ecommerce-admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin